image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: glad2os/dine.gateway

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
  only:
    - master